### PR TITLE
Perps page update

### PR DESCRIPTION
**Pull request by fritzschoff**
- removed sanity and cms stuff
- removed unused assets
- added new perps page
- cleanup in general

### CODE REVIEW

**Review by bachstatter — CHANGES_REQUESTED** [review]
"See integrator" doesn't do anything when I click it.
Screenshot 2023-05-05 at 4 14 06 pm

Explore synths goes to a page that doesn't exist
Screenshot 2023-05-05 at 4 13 43 pm

Footer left/right padding looks a bit off (homepage only). 
Screenshot 2023-05-05 at 4 13 34 pm

**Review by jmzwar — CHANGES_REQUESTED** [review]
Header height looks much smaller than other pages.
Screen Shot 2023-05-05 at 4 19 45 pm

**Review by jmzwar — CHANGES_REQUESTED** [review]
Decentrex link goes to kwenta.

Some padding on button not quite correct 
Screen Shot 2023-05-08 at 9 11 57 pm

Images look slightly rasterised?
Screen Shot 2023-05-08 at 9 12 54 pm

Also header still different height on different routes

**Review by bachstatter — APPROVED** [review]

**Review by jmzwar — APPROVED** [review]
Looks much better

**Pull request merged**
